apiVersion: apps/v1
kind: Deployment
metadata:
  name: shypple
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: shypple
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"