apiVersion: v1
kind: Service
metadata:
  labels:
    app: shypple
  name: shypple
spec:
  ports:
  - name: 8000-tcp
    port: 8000
  selector:
    deployment: shypple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shypple
  name: shypple
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: shypple
  template:
    metadata:
      labels:
        deployment: shypple
    spec:
      containers:
      - name: shypple
        env:
        - name: REDIS_HOST
          value: redis
        image: manish20/shypple:v8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        startupProbe:
          exec:
            command:
            - "cat"
            - "/code/app/myapp.log"
          initialDelaySeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          timeoutSeconds: 5
      restartPolicy: Always